resources:
  - name: concourse-generic-scripts
    type: git
    source:
      uri: https://github.com/sayden/concourse-generic-scripts.git
      branch: master
  
  - name: source-code
    type: git
    source:
      - uri: https://github.com/sayden/concourse-generic-scripts.git
      - branch: master
      - disable_ci_skip: true

jobs:
  - name: generate-compressed-file
    plan:
      - get: concourse-generic-scripts
        trigger: true
      - put: final-file
        resource: source-code
        params:
          repository: concourse-generic-scripts/examples
          username: sayden
          password: {{password}}

      - task: generate-compressed-fil-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              - repository: golang
              - tag: 1.7.1
          inputs:
          - name: concourse-generic-scripts
          run:
            path: sh
            args:
            - -exc
            - |
              tar -zcvf concourse-scripts.tar.gz concourse-generic-scripts
              mv concourse-scripts.tar.gz compressed-file
          outputs:
          - name: compressed-file
