resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/thehivecorporation/raccoon.git
      branch: develop

  - name: concourse-generic-scripts
    type: git
    source:
      uri: https://github.com/sayden/concourse-generic-scripts.git
      branch: master
      username: sayden
      password: {{password}}

jobs:
  - name: unit-tests
    plan:
      - aggregate:
        - get: repo
        - get: concourse-generic-scripts
          trigger: true
      - task: unit-test-task
        file: concourse-generic-scripts/go/unit-test-task.yml

  - name: integration-tests
    plan:
      - aggregate:
        - get: repo
          passed: [unit-tests]
          trigger: true
        - get: concourse-generic-scripts
          trigger: true
      - task: integration-test-task
        file: concourse-generic-scripts/go/integration-test-task.yml
  
  - name: build-binary
    plan:
      - aggregate:
        - get: repo
          passed: [unit-tests]
          trigger: true
        - get: concourse-generic-scripts
          trigger: true
      - task: build-binary
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              - repository: golang
              - tag: 1.7.1
          inputs:
            - name: repo
              path: gopath/src/github.com/thehivecorporation/raccoon
          run:
            path: sh
            args:
            - -exc
            - |
              export ROOT=$(pwd)
              export GOPATH=$(pwd)/gopath
              git clone https://github.com/sayden/concourse-generic-scripts.git
              cd $GOPATH/src/github.com/thehivecorporation/raccoon
              go build -o $ROOT/concourse-generic-scripts/releases-examples/raccoon
              cd $ROOT/concourse-generic-scripts
              git config --global user.email "mariocaster@gmail.com"
              git config --global user.name "sayden"
              git add .
              git commit -m "Test"
          outputs:
            - name: binary
              path: concourse-generic-scripts

      - put: concourse-generic-scripts
        params:
          repository: binary